version: "4"
services:
  app:
    container_name: App
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
      - server
  server:
    container_name: Server
    restart: always
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - logs:/usr/src/server/logs
    depends_on:
      - database
    links:
      - database
    command: yarn start
  database:
    container_name: Postgres
    image: "postgres:14.2"
    ports: 
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    expose:
      - 5432
volumes:
  pgdata : {}
  logs: {}